services:
  database:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: emergency_bed
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
