events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=geocache:10m max_size=1g inactive=48h use_temp_path=off;

    server {
        listen 80;
        server_name localhost;

        location /api-geo/ {
            proxy_pass https://data.geopf.fr/geocodage/;
            
            proxy_ssl_server_name on;
            proxy_set_header Host data.geopf.fr;

            proxy_cache geocache;
            
            proxy_ignore_headers Cache-Control Expires;
            
            proxy_cache_valid 200 48h; 
            proxy_cache_valid 404 400 1m;

            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}