spring.application.name=emergency-bed-service

# Logging
logging.level.root=error
logging.level.fr.medhead=info
logging.level.org.springframework.boot.autoconfigure.h2=info

# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/emergency_bed
spring.datasource.username=api_user
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true